# Generated by Django 5.0 on 2026-02-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('enterprise_id', models.IntegerField()),
                ('pm_user_id', models.IntegerField(null=True)),
                ('team_lead_id', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Active', 'Active'), ('OnHold', 'OnHold'), ('Completed', 'Completed')], default='Planning', max_length=20)),
                ('budget_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('budget_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(null=True)),
                ('health_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('team_size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('PM', 'PM'), ('Analyst', 'Analyst'), ('TL', 'Team Leader'), ('SeniorDev', 'SeniorDev'), ('JuniorDev', 'JuniorDev'), ('Vendor', 'Vendor')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('enterprise_id', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('projects_assigned', models.JSONField(blank=True, null=True)),
                ('activity_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
